version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  wolfram-language-paclet-test:
    docker:
      - image: maxitg/set-replace-wl-ci:12.1.1
        auth:
          username: maxitg
          password: $DOCKERHUB_PASSWORD
    parallelism: 4

    steps:
      - checkout

      - run:
          name: Build
          command: ./build.wls

      - store_artifacts:
          path: ./LibraryResources/

      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Copy libraries from other platforms
          command: cp -r /tmp/workspace/* ./LibraryResources/

      - run:
          name: Install
          command: ./install.wls

      - store_artifacts:
          path: ./BuiltPaclets/

      - run:
          name: Reinstall
          command: ./install.wls

      - run:
          name: Test
          command: |
            if [ $CIRCLE_NODE_INDEX -eq 2 ]
            then
              testsToRun=matching
            elif [ $CIRCLE_NODE_INDEX -eq 3 ]
            then
              testsToRun=WolframModel
            else
              testsToRun=$(circleci tests glob "Tests/*.wlt" \
                | sed "/Tests\/performance.wlt/d" \
                | sed "/Tests\/matching.wlt/d" \
                | sed "/Tests\/WolframModel.wlt/d" \
                | circleci tests split --total=2 --split-by=filesize \
                | sed "s/\.wlt//" \
                | sed "s/Tests\///")
            fi
            ./.circleci/test.sh $testsToRun

      - run:
          name: Performance Test
          command: |
            if [ $CIRCLE_NODE_INDEX -eq 0 ]
            then
              ./performanceTest.wls master HEAD 2
            fi

  macos-build:
    macos:
      xcode: 12.2.0

    steps:
      - checkout

      - run:
          name: Install Homebrew
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - run:
          name: Install Dependencies
          command: |
            brew install cmake gmp pkg-config

      - run:
          name: Build
          command: scripts/buildLibraryResources.sh

      - persist_to_workspace:
          root: LibraryResources
          paths:
            - MacOSX-x86-64

      - store_artifacts:
          path: ./LibraryResources/

  windows-build:
    executor:
      name: win/default
      shell: bash.exe

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            apt-get install cmake libgmp-dev

      - run:
          name: Build
          command: scripts/buildLibraryResources.sh

      - persist_to_workspace:
          root: LibraryResources
          paths:
            - Windows-x86-64

      - store_artifacts:
          path: ./LibraryResources/

workflows:
  version: 2
  build-and-test:
    jobs:
#     - macos-build
      - windows-build
#     - wolfram-language-paclet-test:
#         requires:
#           - macos-build
#           - windows-build
